[versions]
agp = "8.7.2"
kotlin = "2.0.21"
ksp = "2.0.21-1.0.26"
composeBom = "2024.12.02"
minSdk = "28"
compileSdk = "35"
targetSdk = "35"
jvmTarget = "21"
yukihookapi = "1.3.2"
kavaref = "1.2.0"
xposedapi = "82"

[libraries]
core-ktx = "androidx.core:core-ktx:1.16.0"
appcompat = "androidx.appcompat:appcompat:1.7.2"
material = "com.google.android.material:material:1.13.0"
activity-compose = "androidx.activity:activity-compose:1.10.1"
recyclerview = "androidx.recyclerview:recyclerview:1.4.0"
lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.8.8"

[plugins.android-application]
id = "com.android.application"

[plugins.kotlin-android]
id = "org.jetbrains.kotlin.android"

[plugins.ksp]
id = "com.google.devtools.ksp"

[plugins.compose-compiler]
id = "org.jetbrains.kotlin.plugin.compose"

[libraries.compose-bom]
group = "androidx.compose"
name = "compose-bom"

[libraries.compose-ui]
group = "androidx.compose.ui"
name = "ui"

[libraries.compose-ui-tooling]
group = "androidx.compose.ui"
name = "ui-tooling-preview"

[libraries.compose-material3]
group = "androidx.compose.material3"
name = "material3"

[libraries.yukihookapi-api]
module = "com.highcapable.yukihookapi:api"

[libraries.yukihookapi-ksp-xposed]
module = "com.highcapable.yukihookapi:ksp-xposed"

[libraries.kavaref-core]
module = "com.highcapable.kavaref:kavaref-core"

[libraries.xposed-api]
module = "de.robv.android.xposed:api"

[plugins.android-application.version]
ref = "agp"

[plugins.kotlin-android.version]
ref = "kotlin"

[plugins.ksp.version]
ref = "ksp"

[plugins.compose-compiler.version]
ref = "kotlin"

[libraries.compose-bom.version]
ref = "composeBom"

[libraries.yukihookapi-api.version]
ref = "yukihookapi"

[libraries.yukihookapi-ksp-xposed.version]
ref = "yukihookapi"

[libraries.kavaref-core.version]
ref = "kavaref"

[libraries.xposed-api.version]
ref = "xposedapi"
