[versions]
agp = "9.1.1"
kotlin = "2.2.0"
ksp = "2.2.0-1.0.30"
composeBom = "2025.11.00"
composeCompiler = "2.2.0"
minSdk = "28"
compileSdk = "35"
targetSdk = "35"
jvmTarget = "21"
yukihookapi = "1.4.0"
kavaref = "1.3.0"
xposedapi = "82"
coreKtx = "1.17.0"
appcompat = "1.8.0"
material = "1.14.0"
activityCompose = "1.12.0"
recyclerview = "1.5.0"
lifecycleRuntimeKtx = "2.9.0"
dependencyAnalysis = "3.6.0"

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }

yukihookapi-api = { module = "com.highcapable.yukihookapi:api", version.ref = "yukihookapi" }
yukihookapi-ksp-xposed = { module = "com.highcapable.yukihookapi:ksp-xposed", version.ref = "yukihookapi" }
kavaref-core = { module = "com.highcapable.kavaref:kavaref-core", version.ref = "kavaref" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposedapi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
dependency-analysis = { id = "com.autonomousapps.dependency-analysis", version.ref = "dependencyAnalysis" }
